### ISSUE TITLE
Create check out for books and supplies that are not available.

### ISSUE THREAD

**Issue by 10758637** [joshzcold/JCold_UVU_MVC#9] opened 2018-04-11 22:56 UTC
![image 4](https://user-images.githubusercontent.com/36175843/38647383-39425edc-3da9-11e8-8421-7e8c2ceef061.png)
![image 5](https://user-images.githubusercontent.com/36175843/38647385-3a4b829a-3da9-11e8-904c-280d8a2d9397.png)
Admin can create checks out for books and supplies that are not available.

**Comment by joshzcold** [comment] 2018-04-12 00:07
ill look into how hard it would be to implement this, but it could be by design that someone could checkout a book multiple times in order to reserve a book ahead of time. Maybe I could make this purpose more clear.

**Comment by joshzcold** [comment] 2018-04-18 23:16
This is would be outside the scope of the delivery. Closing

**Closed as completed by joshzcold** 2018-04-18 23:16 UTC
Labels: enhancement
